---
jobs:
  - name: helloworld
    plan:
      - task: echo-message
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: echo
            args: ["Hello world!"]
